.github/workflows/approve-and-merge-dispatch.yml
.github/workflows/commands-for-testing-tool.yml
.github/workflows/deploy-oss-catalog.yml
.github/workflows/gke-kube-test-command.yml
.github/workflows/gradle.yml
.github/workflows/label-github-issues-by-context.yml
.github/workflows/label-github-issues-by-path.yml
.github/workflows/label-prs-by-context.yml
.github/workflows/notify-on-push-to-master.yml
.github/workflows/publish-command.yml
.github/workflows/publish-helm-charts.yml
.github/workflows/publish-oss-for-cloud.yml
.github/workflows/release-airbyte-os.yml
.github/workflows/slash-commands.yml
.github/workflows/terminate-zombie-build-instances.yml

As per [#2641](https://app.zenhub.com/workspaces/production-engineering-632380080186f5001a13d1dd/issues/gh/airbytehq/airbyte-cloud/2641) updating GH workflows in cloud repo to reflect changes in PAT usage

update workflows as per new PAT usage scheme

---

settings.gradle

A reference to airbyte-integrations in settings.gradle was leading to a failing gradle build.
I fixed it by removing it
Sanity check, this should be completely fine to do as these files are no longer a part of platform correct?

Remove airbyte-integration reference in settings.gradle

---

airbyte-config/config-models/src/main/java/io/airbyte/config/CatalogDefinitionsConfig.java

Use an API to make this more resilient to the underlying technology serving it
This now points to our ELB fronting a "backend bucket" in GCS

update remote catalog url to be not gcs anymore

---

.github/workflows/gradle.yml
.github/workflows/publish-oss-for-cloud.yml

This is a temporary solution to enable building docs into the frontend artifact from the connectors repo until connector metadata service is live.
We clone connectors repo HEAD and wholesale copy the entire docs folder over to be consumed by frontend build. This is basically identical to how it worked in the monorepo from the end artifact perspective - though if someone wants to test and work with this behavior locally it forces them to copy over the relevant docs directly - so it is a bit of a DevEx regression.
*If unsure, leave it blank.*
We get docs for end users in the platform after this :)

pull docs from connectors repo for fe build

---

airbyte-webapp/packages/vite-plugins/doc-middleware.ts

Since the connector docs are no longer part of `airbyte-platform`, but only of `airbytehq/airbyte`, we can't always load them locally during development of the frontend anymore.
This adjusts our middleware so that:
* if you don't have the `airbytehq/airbyte` repository checked out in parallel, the docs are loaded from GitHub directly.
* If you have the repository checked out in parallel, docs will load from the parallel checked out repository locally, so you can make edits and preview it directly.
You'll see a message on the command line indicating which mode you're running in:

🪟 🔧 Adjust doc middleware for new repo structure

---

charts/airbyte/templates/env-configmap.yaml

Migrated from https://github.com/airbytehq/airbyte/pull/22697
Issue of missing STRICT_COMPARISON_NORMALIZATION_WORKSPACES and STRICT_COMPARISON_NORMALIZATION_TAG from configmap helm chart:
https://github.com/airbytehq/airbyte/issues/22687
Add missing configs in env.

fix: missing from configmap

---

charts/airbyte/templates/_helpers.tpl
charts/airbyte/values.yaml

Allows overriding the DATABASE_URL environment variable in the Helm componen
This allows helm charts to connect to an external database that require
parameters such as SSL mode.
Migrated-From: airbytehq/airbyte#22521
Fixes: airbytehq/airbyte#17995
A new helm chart parameter has been added to the top-level `airbyte` chart
`externalDatabase.jdbcUrl`
If this is set, it will be used instead of constructing the JDBC URL from the individual components.
1. `charts/airbyte/templates/_helpers.tpl`
2. `charts/airbyte/values.yaml`
*If you know that your PR is backwards-compatible and can be simply reverted or rolled back, check the YES box.*
*Otherwise if your PR has a breaking change, like a database migration for example, check the NO box.*
*If unsure, leave it blank.*
No impact expected. This is …

helm: add externalDatabase.jdbcUrl configuration

---

airbyte-featureflag/src/main/kotlin/Client.kt
airbyte-featureflag/src/main/kotlin/Context.kt
airbyte-featureflag/src/test/kotlin/ContextTest.kt

- remove `user` attribute from `Workspace` context
- this was a left-over from an early version of the feature-flag client which only adds confusion
- 🔪

remove optional user from Workspace context

---

airbyte-api/build.gradle

* In `airbytehq/airbyte` we moved the api docs into the `docs/` folder so that it could be show in docs.airbyte.com. That's not relevant anymore and docs.airbyte.com does not use these docs anymore anyway.

remove tasks that moves api docs into docs/ (not relevant in new repo)

---

airbyte-webapp/packages/vite-plugins/doc-middleware.ts

This PR ensures that serving local docs will work no matter if you're running from `airbyte-platform` or `airbyte-platform-internal` (which will be the case next week). In `airbyte-platform-internal` the OSS code will be nested under `/oss` and thus we need to look one folder higher to find the parallel checked out `airbyte` folder for local serving docs.
This PR tries both pathes now. We decided for the simple path checking solution over actually using git to retrieve the root command, to also work in case users would download the files via zip and not have a git repository instantiated.

🪟 🔧 Enable local docs for airbyte-platform-internal

---

.bumpversion.cfg

:bug: fix: bump version entries in cfg to not have non-existant paths
https://github.com/airbytehq/airbyte/actions/runs/4239281966/jobs/7367197306
```
Run ./tools/bin/bump_version.sh
++ grep -w VERSION .env
++ cut -d= -f2
+ PREV_VERSION=0.40.32
++ git rev-parse HEAD
+ GIT_REVISION=37be4c6fcc84d6212847b56bcfe305799c9607dd
+ pip install bumpversion
Collecting bumpversion
Downloading bumpversion-0.6.0-py2.py3-none-any.whl (8.4 kB)
Collecting bump2version
Downloading bump2version-1.0.1-py2.py3-none-any.whl (22 kB)
Installing collected packages: bump2version, bumpversion
Successfully installed bump2version-1.0.1 bumpversion-0.6.0
+ bumpversion patch
Traceback (most recent call last):
File "/actions-runner/_work/_tool/Python/3.9.16/x64/bin/bumpversion", line 8, in <module>
sys.exit(main())
File …
```

:bug: fix: bump version entries in cfg to not have non-existant paths

---

build.gradle

- part of airbytehq/airbyte-platform-internal#4475
- replace dynamic group name `group = "io.${rootProject.name}...` with `group = "io.airbyte`...
- the dynamic group doesn't play nice with the inline oss builds

replace dynamic group name with airbyte

---

airbyte-webapp/src/pages/connectorBuilder/ConnectorBuilderLandingPage/ConnectorBuilderLandingPage.tsx

This PR fixes the issue that navigating back after going to the builder UI currently doesn't work.
The problem is that the user is redirected from the landing page to the edit page, but this navigation is writing a new history entry, so navigating "back" will lead the user to the landing page again, which will immediately redirect them again.
This PR sets the replace option which replaces the landing page history entry instead of writing a new one.
* Enable the builder navigation links experiment (`.experiments.json`):
```
{
"connectorBuilder.showNavigationLinks": true
}
```
* Click the "Builder" nav item
* Click back button
* You get back to where you came from

🪟🐛 Connector builder: Replace instead of navigate

---

airbyte-featureflag/src/main/kotlin/Flags.kt
airbyte-workers/src/main/java/io/airbyte/workers/config/ActivityBeanFactory.java
airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java
airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/FeatureFlagFetchActivity.java
airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/FeatureFlagFetchActivityImpl.java
airbyte-workers/src/test/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowTest.java
airbyte-workers/src/test/java/io/airbyte/workers/temporal/scheduling/activities/FeatureFlagFetchActivityTest.java

Migrated from https://github.com/airbytehq/airbyte/pull/22960
In order to be able to use feature flags within the ConnectionManagerWorkflow, we need to introduce a new activity that fetches the feature flags. This is because we can't directly use the feature flag client in the workflow due to the deterministic constraints of temporal workflows.
This will be used to add a feature flag for https://github.com/airbytehq/airbyte/pull/21899
- Add a new FeatureFlagFetchActivity that runs as the first activity in the ConnectionManagerWorkflow
- Set up the activity to fetch some feature flags. Right now this is looking up an unrelated feature flag, but it used to set up the plumbing to be able to fetch an actually useful flag.
- Update tests

add activity to fetch feature flags

---

airbyte-featureflag/src/main/kotlin/Flags.kt
flags.yml

Add a feature flag to enable commit states asap.
Closes https://github.com/airbytehq/airbyte/issues/23043
No impact, adding a flag, not plugged and currently off.

Add CommitStatesAsap feature flag

---

airbyte-api/src/main/openapi/config.yaml
airbyte-commons-server/src/main/java/io/airbyte/commons/server/converters/JobConverter.java
airbyte-commons-server/src/test/java/io/airbyte/commons/server/converters/JobConverterTest.java
airbyte-webapp/src/components/JobItem/utils.ts

* close https://github.com/airbytehq/airbyte/issues/23280
* Pre-emptively update naming before starting to [return failure reasons in api response for synchronous jobs](https://github.com/airbytehq/airbyte/issues/18514), in order to avoid confusion around these jobs not being attempt-based
1. `airbyte-api/src/main/openapi/config.yaml`
2. Resulting changes in other files, which put the failure information into the API response and read information from the API response
*If you know that your PR is backwards-compatible and can be simply reverted or rolled back, check the YES box.*
*Otherwise if your PR has a breaking change, like a database migration for example, check the NO box.*
*If unsure, leave it blank.*
None

Rename AttemptFailureX -> FailureX API objects for reuse in non-attempt based jobs

---

airbyte-webapp/src/components/connection/CatalogTree/CatalogSection.tsx
airbyte-webapp/src/components/connection/CatalogTree/next/SyncModeSelect.tsx
airbyte-webapp/src/components/connection/CatalogTree/streamConfigHelpers/updateStreamSyncMode.test.ts
airbyte-webapp/src/components/connection/CatalogTree/streamConfigHelpers/updateStreamSyncMode.ts
airbyte-webapp/src/test-utils/mock-data/mockAirbyteStream.ts

Migration of https://github.com/airbytehq/airbyte/pull/22559
Closes https://github.com/airbytehq/airbyte/issues/21817
Ensures that source-defined cursors and primary keys are automatically selected when changing sync modes. Users may deselect a primary key or cursor when the sync mode is `full_refresh` or the destination sync mode is `overwrite`. If they switch back to an `incremental` or `append_dedup` sync mode, we need to ensure that these source-defined fields are automatically selected.
This is a frontend change only and is easily revertible.

🪟 🐛 Ensure source-defined PK and cursor fields are selected when switching sync modes

---

airbyte-webapp/src/components/connection/CatalogDiffModal/DiffAccordionHeader.module.scss
airbyte-webapp/src/components/connection/CatalogDiffModal/DiffAccordionHeader.tsx
airbyte-webapp/src/components/connection/CatalogDiffModal/DiffSection.module.scss
airbyte-webapp/src/components/connection/CatalogDiffModal/DiffSection.tsx
airbyte-webapp/src/components/connection/CatalogDiffModal/FieldRow.module.scss
airbyte-webapp/src/components/connection/CatalogDiffModal/FieldRow.tsx
airbyte-webapp/src/components/connection/CatalogDiffModal/FieldSection.module.scss
airbyte-webapp/src/components/connection/CatalogDiffModal/FieldSection.tsx
airbyte-webapp/src/components/connection/CatalogDiffModal/StreamRow.module.scss
airbyte-webapp/src/components/connection/CatalogDiffModal/StreamRow.tsx
airbyte-webapp/src/components/connection/CatalogDiffModal/index.stories.tsx
airbyte-webapp/src/components/connection/CatalogDiffModal/utils.tsx
airbyte-webapp/src/scss/_mixins.scss

Migration of https://github.com/airbytehq/airbyte/pull/22610
Related to https://github.com/airbytehq/airbyte/issues/22493
This change mainly fixes a few of the issues in the catalog diff modal
* Long names for namespace, stream name, or field name overflowing to the next column. Now, these fields will be truncated with an ellipsis
* Field names were not showing the full path with dot notation, which made it confusing. For example, instead of showing that "user.name" and "company.name" were added to the stream, it would show the last part of the path so you would see what seems to be a duplicate "name" entry.
* Some of the column names were misaligned, and now they are not
Before:
After:
* Lots of CSS work
* Added mixin for text overflow issues
* Updated storybook to include long names as …

🪟 🎨 🐛 Fix long name overflow and field path names in Catalog Diff modal

---

airbyte-webapp/src/components/ui/StepsMenu/Step.tsx
airbyte-webapp/src/components/ui/StepsMenu/StepsMenu.tsx
airbyte-webapp/src/hooks/services/ConnectionEdit/ConnectionEditService.tsx
airbyte-webapp/src/pages/connections/ConnectionPage/ConnectionPageTitle.tsx

Migration of https://github.com/airbytehq/airbyte/pull/22844
Resolves https://github.com/airbytehq/airbyte/issues/22628
Disables the tabs while the schema is refreshing. _Does not hide them_
Add disabled functionality to StepsMenu and Steps components

Disable connection edit tabs during schema refresh

---

charts/airbyte-metrics/templates/deployment.yaml

Resolves https://github.com/airbytehq/airbyte/issues/23226
Currently the airbyte-metrics pod does not start up due to being unable to find the env. More info in the issue linked above, but I was able to get it to start normally with the change included in this PR.
Maybe this change was meant to be included in https://github.com/airbytehq/airbyte/pull/16131?
This PR brings the airbyte-metrics deployment.yaml template in conformance with other charts pulling this secret.
a couple examples of the pattern used elsewhere that I've copied:
https://github.com/airbytehq/airbyte-platform/blob/15a34b8af95e9dbaf4c07980b3f09d724072dc8b/charts/airbyte-server/templates/deployment.yaml#L77-L81
https://github.com/airbytehq/airbyte-platform/blob/15a34b8af95e9dbaf4c07980b3f09d724072dc8b/charts/airbyte-tempo …

Fix DATABASE_PASSWORD env for airbyte-metrics helm chart

---

airbyte-connector-builder-server/connector_builder/generated/models/http_response.py
airbyte-connector-builder-server/connector_builder/impl/default_api.py
airbyte-connector-builder-server/src/main/openapi/openapi.yaml
airbyte-connector-builder-server/unit_tests/connector_builder/impl/test_default_api.py
airbyte-webapp/src/components/connectorBuilder/StreamTestingPanel/PageDisplay.tsx

Migrates https://github.com/airbytehq/airbyte/issues/20764 after the platform monorepo split
joe wrote the FE and I wrote the connector builder changes
For APIs with responses that were non-object responses encapsulated in `{ ... }`. The connector builder read() would fail. It is perfectly reasonable for a API to response with an array of elements `[ ... ]` and potentially even string input. This change should allow for both.
The connector builder server no longer parsed response output into a json object because it might not be one. Instead we pass along the string output and let the frontend handle deserializing it back into the appropriate object to display back in the test output window
1. `default_api.py`
2. `PageDisplay.tsx`

[Migration] [Connector Builder] Return string format to allow for connector read() that return non-object responses

---

airbyte-commons/src/main/java/io/airbyte/commons/features/EnvVariableFeatureFlags.java
airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java
airbyte-workers/src/test/java/io/airbyte/workers/temporal/sync/NormalizationActivityImplTest.java
charts/airbyte/templates/env-configmap.yaml
charts/airbyte/values.yaml

This is a new version of strict_comparison normalization with latest changes from master. Bump the default env var values to the new tag.
Question for reviewer: I don't need to replicate these changes into the connectors repo, right? E.g. https://github.com/airbytehq/airbyte/blob/c55a81bbcb9ca0999949fb0ed0a20bfbcc425525/airbyte-commons/src/main/java/io/airbyte/commons/features/EnvVariableFeatureFlags.java#L77

Normalization: update to strict_comparison2

---

airbyte-webapp/src/components/ui/Paginator/Paginator.module.scss
airbyte-webapp/src/components/ui/Paginator/Paginator.tsx

Closes https://github.com/airbytehq/airbyte-platform-internal/issues/4636
Demo: https://www.loom.com/share/7a56ad4a5cb742dda5f8e37b9a7212bf
Adds a CSS class `disabled` which greys out member classes, and modifies the `button` class styling to grey out instances with the `.disabled` class and prevent changing their mouse cursor. Then it uses `react-paginate`'s `[disabledClassName](https://github.com/AdeleD/react-paginate#props)` property to apply the `.disabled` class to the prev/next buttons when the first/last page is selected.

Connector Builder UI: hide next page icon if last response page is selected

---

.github/workflows/gradle.yml
.github/workflows/publish-oss-for-cloud.yml

Fixes the doc download script. This currently copied `docs` **into** `./docs` (i.e. created a `./docs/docs` folder) and thus had a wrong nesting layer.
Changing this to only copy the actual 2 folder we need (and also making sure they land in the right pathes). Also validate that a file we know should exist actually exist in the right path, otherwise fail the build.
I validated that the docs are bundled by checking inside the `airbyte/webapp:dev-c42ae05a14` image that has been published by this task, that it contains the docs under `/usr/share/nginx/html/docs`.

🪟 🐛 Fix docs download

---

airbyte-webapp/src/pages/connections/ConnectionSettingsPage/ConnectionSettingsPage.tsx
airbyte-webapp/src/pages/connections/ConnectionSettingsPage/SchemaUpdateNotifications.tsx

Resolves https://github.com/airbytehq/airbyte/issues/22562
Replaces https://github.com/airbytehq/airbyte/pull/23104
Re-enables the schema update notifications.
* Removes commented out code
* Fixes an issue where the switch was rendering poorly due to flexboxes. Needed to be wrapped in a div

🪟 🎉 Re-enable schema update notifications

---

.github/workflows/publish-helm-charts.yml

master is now main because we moved repos
this will enable builds to trigger when they hit main

Helm chart publish trigger fix
